package com.example.thirtydays.model

import com.example.thirtydays.R

object RecipesRepository {
    val recipes = listOf(
        Recipe(
            R.string.recipe1,
            R.string.description1,
            R.drawable.spaghetti1
        ),
        Recipe(
            R.string.recipe2,
            R.string.description2,
            R.drawable.chicken2
        ),
        Recipe(
            R.string.recipe3,
            R.string.description3,
            R.drawable.beef3
        ),
        Recipe(
            R.string.recipe4,
            R.string.description4,
            R.drawable.vegetable4
        ),
        Recipe(
            R.string.recipe5,
            R.string.description5,
            R.drawable.caprese5
        ),
        Recipe(
            R.string.recipe6,
            R.string.description6,
            R.drawable.padtahi6
        ),
        Recipe(
            R.string.recipe7,
            R.string.description7,
            R.drawable.chilli7
        ),
        Recipe(
            R.string.recipe8,
            R.string.description8,
            R.drawable.mushroom8
        ),
        Recipe(
            R.string.recipe9,
            R.string.description9,
            R.drawable.sushi9
        ),
        Recipe(
            R.string.recipe10,
            R.string.description10,
            R.drawable.salmon10
        ),
        Recipe(
            R.string.recipe11,
            R.string.description11,
            R.drawable.chicken_curry11
        ),
        Recipe(
            R.string.recipe12,
            R.string.description12,
            R.drawable.guacamole12
        ),
        Recipe(
            R.string.recipe13,
            R.string.description13,
            R.drawable.beef_tacos13
        ),
        Recipe(
            R.string.recipe14,
            R.string.description14,
            R.drawable.lemon_garlic_pasta14
        ),
        Recipe(
            R.string.recipe15,
            R.string.description15,
            R.drawable.chicken_parmesan15
        ),
        Recipe(
            R.string.recipe16,
            R.string.description16,
            R.drawable.yum_soup16
        ),
        Recipe(
            R.string.recipe17,
            R.string.description17,
            R.drawable.vegetable_lasagna17
        ),
        Recipe(
            R.string.recipe18,
            R.string.description18,
            R.drawable.beef_bulgogi18
        ),
        Recipe(
            R.string.recipe19,
            R.string.description19,
            R.drawable.ratatouille19
        ),
        Recipe(
            R.string.recipe20,
            R.string.description20,
            R.drawable.pesto20
        ),
        Recipe(
            R.string.recipe21,
            R.string.description21,
            R.drawable.honey_soy21
        ),
        Recipe(
            R.string.recipe22,
            R.string.description22,
            R.drawable.shakshuka22
        ),
        Recipe(
            R.string.recipe23,
            R.string.description23,
            R.drawable.beef_pho23
        ),
        Recipe(
            R.string.recipe24,
            R.string.description24,
            R.drawable.falafel24
        ),
        Recipe(
            R.string.recipe25,
            R.string.description25,
            R.drawable.beef_wellington25
        ),
        Recipe(
            R.string.recipe26,
            R.string.description26,
            R.drawable.pumpkin_soup26
        ),
        Recipe(
            R.string.recipe27,
            R.string.description27,
            R.drawable.chicken_shawarma27
        ),
        Recipe(
            R.string.recipe28,
            R.string.description28,
            R.drawable.eggplant28
        ),
        Recipe(
            R.string.recipe29,
            R.string.description29,
            R.drawable.cevichejpg29
        ),
        Recipe(
            R.string.recipe30,
            R.string.description30,
            R.drawable.noodle_soup30
        ),
    )
}